//>>built
(function(m,h){var d,q=function(){},t=function(n){for(var a in n)return 0;return 1},u={}.toString,w=function(n){return"[object Function]"==u.call(n)},s=function(n){return"[object String]"==u.call(n)},r=function(n){return"[object Array]"==u.call(n)},b=function(n,a){if(n)for(var c=0;c<n.length;)a(n[c++])},k=function(n,a){for(var c in a)n[c]=a[c];return n},l=function(n,a){return k(Error(n),{src:"dojoLoader",info:a})},a=1,e=function(){return"_"+a++},c=function(n,a,b){return Qa(n,a,b,0,c)},g=this,f=g.document,
x=f&&f.createElement("DiV"),p=c.has=function(n){return w(E[n])?E[n]=E[n](g,f,x):E[n]},E=p.cache=h.hasCache;p.add=function(n,a,c,b){(void 0===E[n]||b)&&(E[n]=a);return c&&p(n)};p.add("host-webworker","undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope);p("host-webworker")&&(k(h.hasCache,{"host-browser":0,dom:0,"dojo-dom-ready-api":0,"dojo-sniff":0,"dojo-inject-api":1,"host-webworker":1}),h.loaderPatch={injectUrl:function(n,a){try{importScripts(n),a()}catch(c){console.error(c)}}});
for(var D in m.has)p.add(D,m.has[D],0,1);var F=0,N=[],y=0,v=q,G=q,A;c.isXdUrl=q;c.initSyncLoader=function(n,a,c){y||(y=n,v=a,G=c);return{sync:"sync",requested:1,arrived:2,nonmodule:3,executing:4,executed:5,syncExecStack:N,modules:B,execQ:Q,getModule:T,injectModule:sa,setArrived:ba,signal:C,finishExec:ha,execModule:ia,dojoRequirePlugin:y,getLegacyMode:function(){return F},guardCheckComplete:ja}};var U=location.protocol,K=location.host;c.isXdUrl=function(n){return/^\./.test(n)?!1:/^\/\//.test(n)?!0:
(n=n.match(/^([^\/\:]+\:)\/+([^\/]+)/))&&(n[1]!=U||K&&n[2]!=K)};p.add("dojo-force-activex-xhr",!f.addEventListener&&"file:"==window.location.protocol);p.add("native-xhr","undefined"!=typeof XMLHttpRequest);if(p("native-xhr")&&!p("dojo-force-activex-xhr"))A=function(){return new XMLHttpRequest};else{var I=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],Z;for(d=0;3>d;)try{if(Z=I[d++],new ActiveXObject(Z))break}catch(ka){}A=function(){return new ActiveXObject(Z)}}c.getXhr=A;p.add("dojo-gettext-api",
1);c.getText=function(n,a,c){var b=A();b.open("GET",ta(n),!1);b.send(null);if(200==b.status||!location.host&&!b.status)c&&c(b.responseText,a);else throw l("xhrFailed",b.status);return b.responseText};var H=new Function("return eval(arguments[0]);");c.eval=function(n,a){return H(n+"\r\n////@ sourceURL\x3d"+a)};var Fa={},C=c.signal=function(n,a){var c=Fa[n];b(c&&c.slice(0),function(n){n.apply(null,r(a)?a:[a])})},O=c.on=function(n,a){var c=Fa[n]||(Fa[n]=[]);c.push(a);return{remove:function(){for(var n=
0;n<c.length;n++)if(c[n]===a){c.splice(n,1);break}}}},J=[],L={},M=[],z={},ca=c.map={},V=[],B={},da="",P={},ea={},W={},X=0,S=function(n){var a,c,b,f;for(a in ea)c=ea[a],(b=a.match(/^url\:(.+)/))?P["url:"+Ra(b[1],n)]=c:"*now"==a?f=c:"*noref"!=a&&(b=la(a,n,!0),P[b.mid]=P["url:"+b.url]=c);f&&f(Ga(n));ea={}},ua=function(n){return n.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(n){return"\\"+n})},ma=function(n,a){a.splice(0,a.length);for(var c in n)a.push([c,n[c],RegExp("^"+ua(c)+"(/|$)"),c.length]);
a.sort(function(n,a){return a[3]-n[3]});return a},Ha=function(n,a){b(n,function(n){a.push([s(n[0])?RegExp("^"+ua(n[0])+"$"):n[0],n[1]])})},va=function(n){var a=n.name;a||(a=n,n={name:a});n=k({main:"main"},n);n.location=n.location?n.location:a;n.packageMap&&(ca[a]=n.packageMap);n.main.indexOf("./")||(n.main=n.main.substring(2));z[a]=n},fa=[],na=function(n,a,f){for(var e in n){"waitSeconds"==e&&(c.waitms=1E3*(n[e]||0));"cacheBust"==e&&(da=n[e]?s(n[e])?n[e]:(new Date).getTime()+"":"");if("baseUrl"==
e||"combo"==e)c[e]=n[e];if("async"==e){var g=n[e];c.legacyMode=F=s(g)&&/sync|legacyAsync/.test(g)?g:!g?"sync":!1;c.async=!F}n[e]!==E&&(c.rawConfig[e]=n[e],"has"!=e&&p.add("config-"+e,n[e],0,a))}c.baseUrl||(c.baseUrl="./");/\/$/.test(c.baseUrl)||(c.baseUrl+="/");for(e in n.has)p.add(e,n.has[e],0,a);b(n.packages,va);for(var x in n.packagePaths)b(n.packagePaths[x],function(n){var a=x+"/"+n;s(n)&&(n={name:n});n.location=a;va(n)});ma(k(ca,n.map),V);b(V,function(n){n[1]=ma(n[1],[]);"*"==n[0]&&(V.star=n)});
ma(k(L,n.paths),M);Ha(n.aliases,J);if(a)fa.push({config:n.config});else for(e in n.config)a=T(e,f),a.config=k(a.config||{},n.config[e]);n.cache&&(S(),ea=n.cache,n.cache["*noref"]&&S());C("config",[n,c.rawConfig])};p("dojo-cdn");var wa=f.getElementsByTagName("script");d=0;for(var Y,aa,xa,oa;d<wa.length;){Y=wa[d++];if((xa=Y.getAttribute("src"))&&(oa=xa.match(/(((.*)\/)|^)dojo\.js(\W|$)/i)))aa=oa[3]||"",h.baseUrl=h.baseUrl||aa,X=Y;if(xa=Y.getAttribute("data-dojo-config")||Y.getAttribute("djConfig"))W=
c.eval("({ "+xa+" })","data-dojo-config"),X=Y}c.rawConfig={};na(h,1);p("dojo-cdn")&&((z.dojo.location=aa)&&(aa+="/"),z.dijit.location=aa+"../dijit/",z.dojox.location=aa+"../dojox/");na(m,1);na(W,1);var pa=function(n){ja(function(){b(n.deps,sa)})},Qa=function(n,a,b,f,p){var g;if(s(n)){if((g=T(n,f,!0))&&g.executed)return g.result;throw l("undefinedModule",n);}r(n)||(na(n,0,f),n=a,a=b);if(r(n))if(n.length){b="require*"+e();for(var x,y=[],v=0;v<n.length;)x=n[v++],y.push(T(x,f));g=k(ya("",b,0,""),{injected:2,
deps:y,def:a||q,require:f?f.require:c,gc:1});B[g.mid]=g;pa(g);var D=qa&&"sync"!=F;ja(function(){ia(g,D)});g.executed||Q.push(g);ga()}else a&&a();return p},Ga=function(n){if(!n)return c;var a=n.require;a||(a=function(c,b,f){return Qa(c,b,f,n,a)},n.require=k(a,c),a.module=n,a.toUrl=function(a){return Ra(a,n)},a.toAbsMid=function(a){return Ia(a,n)},a.syncLoadNls=function(a){a=la(a,n);var c=B[a.mid];if(!c||!c.executed)if($=P[a.mid]||P["url:"+a.url])za($),c=B[a.mid];return c&&c.executed&&c.result});return a},
Q=[],Aa=[],R={},bb=function(a){a.injected=1;R[a.mid]=1;a.url&&(R[a.url]=a.pack||1);Sa()},ba=function(a){a.injected=2;delete R[a.mid];a.url&&delete R[a.url];t(R)&&(Ba(),"xd"==F&&(F="sync"))},cb=c.idle=function(){return!Aa.length&&t(R)&&!Q.length&&!qa},Ja=function(a,c){if(c)for(var b=0;b<c.length;b++)if(c[b][2].test(a))return c[b];return 0},Ta=function(a){var c=[],b,f;for(a=a.replace(/\\/g,"/").split("/");a.length;)b=a.shift(),".."==b&&c.length&&".."!=f?(c.pop(),f=c[c.length-1]):"."!=b&&c.push(f=b);
return c.join("/")},ya=function(a,b,f,e){var g=c.isXdUrl(e);return{pid:a,mid:b,pack:f,url:e,executed:0,def:0,isXd:g,isAmd:!!(g||z[a]&&z[a].isAmd)}},Ua=function(a,c,f,e,g,x,y,k,v){var D,E,d,F;F=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||F&&!c)return ya(0,a,0,a);a=Ta(F?c.mid+"/../"+a:a);if(/^\./.test(a))throw l("irrationalPath",a);c&&(d=Ja(c.mid,x));(d=(d=d||x.star)&&Ja(a,d[1]))&&(a=d[1]+a.substring(d[3]));c=(oa=a.match(/^([^\/]+)(\/(.+))?$/))?oa[1]:"";(D=f[c])?a=c+"/"+(E=oa[3]||D.main):c="";var q=
0;b(k,function(c){var b=a.match(c[0]);b&&0<b.length&&(q=w(c[1])?a.replace(c[0],c[1]):c[1])});if(q)return Ua(q,0,f,e,g,x,y,k,v);if(f=e[a])return v?ya(f.pid,f.mid,f.pack,f.url):e[a];e=(d=Ja(a,y))?d[1]+a.substring(d[3]):c?D.location+"/"+E:p("config-tlmSiblingOfDojo")?"../"+a:a;/(^\/)|(\:)/.test(e)||(e=g+e);return ya(c,a,D,Ta(e+".js"))},la=function(a,b,f){return Ua(a,b,z,B,c.baseUrl,f?[]:V,f?[]:M,f?[]:J)},Va=function(a,c,b){return a.normalize?a.normalize(c,function(a){return Ia(a,b)}):Ia(c,b)},Wa=0,T=
function(a,c,b){var f,e;(f=a.match(/^(.+?)\!(.*)$/))?(e=T(f[1],c,b),"sync"==F&&!e.executed&&(sa(e),2===e.injected&&!e.executed&&ja(function(){ia(e)}),e.executed?Ca(e):Q.unshift(e)),5===e.executed&&!e.load&&Ca(e),e.load?(f=Va(e,f[2],c),a=e.mid+"!"+(e.dynamic?++Wa+"!":"")+f):(f=f[2],a=e.mid+"!"+ ++Wa+"!waitingForPlugin"),a={plugin:e,mid:a,req:Ga(c),prid:f}):a=la(a,c);return B[a.mid]||!b&&(B[a.mid]=a)},Ia=c.toAbsMid=function(a,c){return la(a,c).mid},Ra=c.toUrl=function(a,c){var b=la(a+"/x",c),f=b.url;
return ta(0===b.pid?a:f.substring(0,f.length-5))},Xa={injected:2,executed:5,def:3,result:3},Ka=function(a){return B[a]=k({mid:a},Xa)},db=Ka("require"),eb=Ka("exports"),fb=Ka("module"),Da={},La=0,Ca=function(a){var c=a.result;a.dynamic=c.dynamic;a.normalize=c.normalize;a.load=c.load;return a},gb=function(a){var c={};b(a.loadQ,function(b){var f=Va(a,b.prid,b.req.module),e=a.dynamic?b.mid.replace(/waitingForPlugin$/,f):a.mid+"!"+f,f=k(k({},b),{mid:e,prid:f,injected:0});B[e]||Ya(B[e]=f);c[b.mid]=B[e];
ba(b);delete B[b.mid]});a.loadQ=0;var f=function(a){for(var b=a.deps||[],f=0;f<b.length;f++)(a=c[b[f].mid])&&(b[f]=a)},e;for(e in B)f(B[e]);b(Q,f)},ha=function(a){c.trace("loader-finish-exec",[a.mid]);a.executed=5;a.defOrder=La++;b(a.provides,function(a){a()});a.loadQ&&(Ca(a),gb(a));for(d=0;d<Q.length;)Q[d]===a?Q.splice(d,1):d++;/^require\*/.test(a.mid)&&delete B[a.mid]},hb=[],ia=function(a,b){if(4===a.executed)return c.trace("loader-circular-dependency",[hb.concat(a.mid).join("-\x3e")]),!a.def||
b?Da:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return Da;var f=a.mid,e=a.deps||[],g,x=[],y=0;for(a.executed=4;g=e[y++];){g=g===db?Ga(a):g===eb?a.cjs.exports:g===fb?a.cjs:ia(g,b);if(g===Da)return a.executed=0,c.trace("loader-exec-module",["abort",f]),Da;x.push(g)}c.trace("loader-run-factory",[a.mid]);var f=a.def,k;N.unshift(a);if(p("config-dojo-loader-catches"))try{k=w(f)?f.apply(null,x):f}catch(v){C("error",a.result=l("factoryThrew",[a,v]))}else k=w(f)?f.apply(null,x):f;a.result=void 0===k&&
a.cjs?a.cjs.exports:k;N.shift(a);ha(a)}return a.result},qa=0,ja=function(a){try{qa++,a()}finally{qa--}cb()&&C("idle",[])},ga=function(){qa||ja(function(){v();for(var a,c,b=0;b<Q.length;)a=La,c=Q[b],ia(c),a!=La?(v(),b=0):b++})};void 0===p("dojo-loader-eval-hint-url")&&p.add("dojo-loader-eval-hint-url",1);var ta="function"==typeof m.fixupUrl?m.fixupUrl:function(a){a+="";return a+(da?(/\?/.test(a)?"\x26":"?")+da:"")},Ya=function(a){var c=a.plugin;5===c.executed&&!c.load&&Ca(c);var b=function(c){a.result=
c;ba(a);ha(a);ga()};c.load?c.load(a.prid,a.req,b):c.loadQ?c.loadQ.push(a):(c.loadQ=[a],Q.unshift(c),sa(c))},$=0,ra=0,Ma=0,za=function(a,b){p("config-stripStrict")&&(a=a.replace(/"use strict"/g,""));Ma=1;if(p("config-dojo-loader-catches"))try{a===$?$.call(null):c.eval(a,p("dojo-loader-eval-hint-url")?b.url:b.mid)}catch(f){C("error",l("evalModuleThrew",b))}else a===$?$.call(null):c.eval(a,p("dojo-loader-eval-hint-url")?b.url:b.mid);Ma=0},sa=function(a){var f=a.mid,e=a.url;if(!a.executed&&!a.injected&&
!(R[f]||a.url&&(a.pack&&R[a.url]===a.pack||1==R[a.url])))if(bb(a),a.plugin)Ya(a);else{var g=function(){Za(a);if(2!==a.injected){if(p("dojo-enforceDefine")){C("error",l("noDefine",a));return}ba(a);k(a,Xa);c.trace("loader-define-nonmodule",[a.url])}F?!N.length&&ga():ga()};if($=P[f]||P["url:"+a.url])c.trace("loader-inject",["cache",a.mid,e]),za($,a),g();else{if(F)if(a.isXd)"sync"==F&&(F="xd");else if(!(a.isAmd&&"sync"!=F)){var x=function(p){if("sync"==F){N.unshift(a);za(p,a);N.shift();Za(a);a.cjs||(ba(a),
ha(a));if(a.finish){p=f+"*finish";var x=a.finish;delete a.finish;Na(p,["dojo",("dojo/require!"+x.join(",")).replace(/\./g,"/")],function(a){b(x,function(c){a.require(c)})});Q.unshift(T(p))}g()}else(p=G(a,p))?(za(p,a),g()):(ra=a,c.injectUrl(ta(e),g,a),ra=0)};c.trace("loader-inject",["xhr",a.mid,e,"sync"!=F]);if(p("config-dojo-loader-catches"))try{c.getText(e,"sync"!=F,x)}catch(y){C("error",l("xhrInjectFailed",[a,y]))}else c.getText(e,"sync"!=F,x);return}c.trace("loader-inject",["script",a.mid,e]);
ra=a;c.injectUrl(ta(e),g,a);ra=0}}},Oa=function(a,b,f){c.trace("loader-define-module",[a.mid,b]);var e=a.mid;if(2===a.injected)return C("error",l("multipleDefine",a)),a;k(a,{deps:b,def:f,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(c){a.cjs.exports=c},config:function(){return a.config}}});for(var g=0;b[g];g++)b[g]=T(b[g],a);F&&!R[e]&&(pa(a),Q.push(a),ga());ba(a);!w(f)&&!b.length&&(a.result=f,ha(a));return a},Za=function(a,c){for(var f=[],e,g;Aa.length;)g=Aa.shift(),c&&(g[0]=c.shift()),
e=g[0]&&T(g[0])||a,f.push([e,g[1],g[2]]);S(a);b(f,function(a){pa(Oa.apply(null,a))})},Ea=0,Ba=q,Sa=q,Ba=function(){Ea&&clearTimeout(Ea);Ea=0},Sa=function(){Ba();c.waitms&&(Ea=g.setTimeout(function(){Ba();C("error",l("timeout",R))},c.waitms))};p.add("ie-event-behavior",f.attachEvent&&"undefined"===typeof Windows&&("undefined"===typeof opera||"[object Opera]"!=opera.toString()));var Pa=function(a,c,b,f){if(p("ie-event-behavior"))return a.attachEvent(b,f),function(){a.detachEvent(b,f)};a.addEventListener(c,
f,!1);return function(){a.removeEventListener(c,f,!1)}},ib=Pa(window,"load","onload",function(){c.pageLoaded=1;"complete"!=f.readyState&&(f.readyState="complete");ib()}),wa=f.getElementsByTagName("script");for(d=0;!X;)if(!/^dojo/.test((Y=wa[d++])&&Y.type))X=Y;c.injectUrl=function(a,c,b){b=b.node=f.createElement("script");var e=Pa(b,"load","onreadystatechange",function(a){a=a||window.event;var b=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(b.readyState))e(),g(),c&&c()}),g=Pa(b,
"error","onerror",function(c){e();g();C("error",l("scriptError",[a,c]))});b.type="text/javascript";b.charset="utf-8";b.src=a;X.parentNode.insertBefore(b,X);return b};c.log=function(){try{for(var a=0;a<arguments.length;a++);}catch(c){}};c.trace=q;var Na=function(a,b,f){var e=arguments.length,g=["require","exports","module"],x=[0,a,b];1==e?x=[0,w(a)?g:[],a]:2==e&&s(a)?x=[a,w(b)?g:[],b]:3==e&&(x=[a,b,f]);c.trace("loader-define",x.slice(0,2));if((e=x[0]&&T(x[0]))&&!R[e.mid])pa(Oa(e,x[1],x[2]));else if(!p("ie-event-behavior")||
Ma)Aa.push(x);else{e=e||ra;if(!e)for(a in R)if((g=B[a])&&g.node&&"interactive"===g.node.readyState){e=g;break}e?(S(e),pa(Oa(e,x[1],x[2]))):C("error",l("ieDefineFailed",x[0]));ga()}};Na.amd={vendor:"dojotoolkit.org"};k(k(c,h.loaderPatch),m.loaderPatch);O("error",function(a){try{if(console.error(a),a instanceof Error)for(var c in a);}catch(b){}});k(c,{uid:e,cache:P,packs:z});if(g.define)C("error",l("defineAlreadyDefined",0));else{g.define=Na;g.require=c;b(fa,function(a){na(a)});var $a=W.deps||m.deps||
h.deps,ab=W.callback||m.callback||h.callback;c.boot=$a||ab?[$a||[],ab]:0}})(this.dojoConfig||this.djConfig||this.require||{},{async:0,hasCache:{"config-selectorEngine":"acme","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:"../put-selector",main:"put",name:"put-selector"},{location:".",name:"dojo"},{location:"../xstyle",name:"xstyle"}]});
require({cache:{"xstyle/core/Rule":function(){define("xstyle/core/Rule",["xstyle/core/expression","put-selector/put","xstyle/core/utils","xstyle/core/Proxy"],function(m,h,d,q){function t(){}function u(a,b,c,g){if(a.calls)for(var f,x=0;x<a.length;x++){var p=a[x];if(p instanceof w){a.hasOwnProperty(x)||(a[x]=p=s(p));var k=p.ref&&p.ref.apply(b,p.getArgs(),c);void 0!==k&&((f||(f=[])).push(k),p.evaluated=!0)}}if(f)return b=m.react(function(){for(var c=0,b=a.slice(),f=0;f<a.length;f++){var e=a[f];e instanceof
w&&e.evaluated&&(b[f-1]=a[f-1].slice(0,-e.caller.length),b[f]=arguments[c++])}return b.join("")}),b.skipResolve=!0,b.apply(this,f);if(!g)return a.toString()}function w(a){this.caller=a;this.args=[]}var s=Object.create||function(a){function b(){}b.prototype=a;return new b},r={"{":"}","[":"]","(":")"},b=m.observe,k=h("div").style;t.prototype={property:function(a){return(this._properties||(this._properties={}))[a]||(this._properties[a]=new q(this.get(a)))},eachProperty:function(a){for(var b=this.values||
0,c=0;c<b.length;c++){var g=b[c];a.call(this,g||"unnamed",b[g])}},fullSelector:function(){return(this.parent?this.parent.fullSelector():"")+(this.selector||"")+" "},newRule:function(a){a=(this.rules||(this.rules={}))[a]=new t;a.disabled=this.disabled;return a},newCall:function(a){return new w(a)},addSheetRule:function(a,b){if(b&&"@"!=a.charAt(0)){var c=this.styleSheet,g=c.cssRules||c.rules,f=-1<this.ruleIndex?this.ruleIndex:g.length;c.addRule(a,b,f);return g[f]}},onRule:function(){var a=this.getCssRule();
if(this.installStyles)for(var b=0;b<this.installStyles.length;b++){var c=this.installStyles[b];a.style[c[0]]=c[1]}},setStyle:function(a,b){this.cssRule?this.cssRule.style[a]=b:(this.installStyles||(this.installStyles=[])).push([a,b])},getCssRule:function(){this.cssRule||(this.cssRule=this.addSheetRule(this.selector,this.cssText));return this.cssRule},get:function(a){return this.values[a]},elements:function(a){var b=this;require(["xstyle/core/elemental"],function(c){c.addRenderer(b,function(c){a(c)})})},
declareDefinition:function(a,b,c){if(!this.disabled){var g=this;if(b.length)if("\x3e"==b[0].toString().charAt(0))a||(this.generator=b,require(["xstyle/core/generate","xstyle/core/elemental"],function(a,c){b=a.forSelector(b,g);c.addRenderer(g,b)}));else{var f=a in k||this.getDefinition(a);if(!c||!f){c=this.definitions||(this.definitions={});var x=b[0];if(x.indexOf&&-1<x.indexOf(","))for(var x=b.join("").split(/\s*,\s*/),p=[],l=0;l<x.length;l++)p[l]=m.evaluate(this,x[l]);b[0]&&"{"==b[0].operator?p=
b[0]:b[1]&&"{"==b[1].operator&&(p=b[1]);p=p||m.evaluate(this,b);if(p.then)var D=p,p={then:function(a){return D.then(function(c){return a(d(c))})}};var d=function(c){c.define&&(c=c.define(a,g));return c};c[a]=d(p);f&&console.warn('Overriding existing property "'+a+'"')}}else c=this.definitions||(this.definitions={}),c[a]=b}},onArguments:function(a,b){var c=a.ref;return c&&c.apply(this,a.getArgs(),b)},setValue:function(a,b,c){if(!this.disabled){var g=this.values||(this.values=[]);g.push(a);g[a]=b;if(a){var f=
a;do{g=(c||this).getDefinition(a);if(void 0!==g){this.cssRule&&(c=this.cssRule.style,a in c&&(c[a]=""));var x=this;return d.when(g,function(a){a=a.splice?a:[a];for(var c=0;c<a.length;c++){var g;d.when(a[c],function(a){g=(a.forParent?a.forParent(x,f):a).put(b)});if(g)return g}})}a=a.substring(0,a.lastIndexOf("-"))}while(a)}f in k&&this._setStyleFromValue(f,b,!0)}},_setStyleFromValue:function(a,e,c){var g=e[0];if(g instanceof t){e=g.values;for(c=0;c<e.length;c++)g=e[c],this._setStyleFromValue(a+("main"==
g?"":"-"+g),e[g])}else{if(e.calls){var f=this,x=u(e,this,a,!0);if(x)return x.forElement?require(["xstyle/core/elemental"],function(c){c.addRenderer(f,function(c){b(x.forElement(c),function(b){c.style[a]=b})})}):b(x,function(c){f.setStyle(a,c)})}c||this.setStyle(a,e)}},forParent:function(a){this.extend(a);var b=this;return{put:function(c){if("defaults"!=c&&c&&"string"==typeof c&&b.values){c=c.toString().split(/,\s*/);for(var g=0;g<c.length;g++){var f=b.values[g];f&&a.setValue(f,c[g],b)}}}}},extend:function(a,
b){var c=this,g=c.cssText,f=c.extraSelector;f&&(a.selector+=f);if(a.cssRule)for(var g=c.cssRule.style,f=a.cssRule.style,x=a.inheritedStyles||(a.inheritedStyles={}),p=0;p<g.length;p++){var k=g[p];if(!f[k]||x[k])f[k]=g[k],x[k]=!0}else a.cssText+=g;"values,variables,calls".replace(/\w+/g,function(b){var f=c[b];f&&(a[b]=s(f))});if(b){if(g=c.definitions)a.definitions=s(g);a.tagName=c.tagName||a.tagName}a.base=c;c.eachProperty(function(c,b){"object"==typeof b&&(b=s(b));a.setValue(c,b)});c.generator&&a.declareDefinition(null,
c.generator)},getDefinition:function(a,b){var c=this;do{var g=c.definitions&&c.definitions[a];void 0===g&&(b&&c[b])&&(g=c[b][a]);c=c.parent}while(void 0===g&&c);return g},newElement:function(){return h((this.tagName||"span")+(this.selector||""))},cssText:""};m.evaluateText=u;var l=w.prototype=new t;l.declareDefinition=l.setValue=function(a,b){this.args.push(b)};l.toString=function(){var a=this.operator;return a+this.args+r[a]};return t})},"dojo/_base/lang":function(){define(["./kernel","../has","../sniff"],
function(m,h){h.add("bug-for-in-skips-shadowed",function(){for(var b in{toString:1})return 0;return 1});var d=h("bug-for-in-skips-shadowed")?"hasOwnProperty valueOf isPrototypeOf propertyIsEnumerable toLocaleString toString constructor".split(" "):[],q=d.length,t=function(b,k,l){l||(l=b[0]&&m.scopeMap[b[0]]?m.scopeMap[b.shift()][1]:m.global);try{for(var a=0;a<b.length;a++){var e=b[a];if(!(e in l))if(k)l[e]={};else return;l=l[e]}return l}catch(c){}},u=Object.prototype.toString,w=function(b,k,l){return(l||
[]).concat(Array.prototype.slice.call(b,k||0))},s=/\{([^\}]+)\}/g,r={_extraNames:d,_mixin:function(b,k,l){var a,e,c,g={};for(a in k)if(e=k[a],!(a in b)||b[a]!==e&&(!(a in g)||g[a]!==e))b[a]=l?l(e):e;if(h("bug-for-in-skips-shadowed")&&k)for(c=0;c<q;++c)if(a=d[c],e=k[a],!(a in b)||b[a]!==e&&(!(a in g)||g[a]!==e))b[a]=l?l(e):e;return b},mixin:function(b,k){b||(b={});for(var l=1,a=arguments.length;l<a;l++)r._mixin(b,arguments[l]);return b},setObject:function(b,k,l){var a=b.split(".");b=a.pop();return(l=
t(a,!0,l))&&b?l[b]=k:void 0},getObject:function(b,k,l){return t(b.split("."),k,l)},exists:function(b,k){return void 0!==r.getObject(b,!1,k)},isString:function(b){return"string"==typeof b||b instanceof String},isArray:function(b){return b&&(b instanceof Array||"array"==typeof b)},isFunction:function(b){return"[object Function]"===u.call(b)},isObject:function(b){return void 0!==b&&(null===b||"object"==typeof b||r.isArray(b)||r.isFunction(b))},isArrayLike:function(b){return b&&void 0!==b&&!r.isString(b)&&
!r.isFunction(b)&&!(b.tagName&&"form"==b.tagName.toLowerCase())&&(r.isArray(b)||isFinite(b.length))},isAlien:function(b){return b&&!r.isFunction(b)&&/\{\s*\[native code\]\s*\}/.test(String(b))},extend:function(b,k){for(var l=1,a=arguments.length;l<a;l++)r._mixin(b.prototype,arguments[l]);return b},_hitchArgs:function(b,k){var l=r._toArray(arguments,2),a=r.isString(k);return function(){var e=r._toArray(arguments),c=a?(b||m.global)[k]:k;return c&&c.apply(b||this,l.concat(e))}},hitch:function(b,k){if(2<
arguments.length)return r._hitchArgs.apply(m,arguments);k||(k=b,b=null);if(r.isString(k)){b=b||m.global;if(!b[k])throw['lang.hitch: scope["',k,'"] is null (scope\x3d"',b,'")'].join("");return function(){return b[k].apply(b,arguments||[])}}return!b?k:function(){return k.apply(b,arguments||[])}},delegate:function(){function b(){}return function(k,l){b.prototype=k;var a=new b;b.prototype=null;l&&r._mixin(a,l);return a}}(),_toArray:h("ie")?function(){function b(b,l,a){a=a||[];for(l=l||0;l<b.length;l++)a.push(b[l]);
return a}return function(k){return(k.item?b:w).apply(this,arguments)}}():w,partial:function(b){return r.hitch.apply(m,[null].concat(r._toArray(arguments)))},clone:function(b){if(!b||"object"!=typeof b||r.isFunction(b))return b;if(b.nodeType&&"cloneNode"in b)return b.cloneNode(!0);if(b instanceof Date)return new Date(b.getTime());if(b instanceof RegExp)return RegExp(b);var k,l,a;if(r.isArray(b)){k=[];l=0;for(a=b.length;l<a;++l)l in b&&k.push(r.clone(b[l]))}else k=b.constructor?new b.constructor:{};
return r._mixin(k,b,r.clone)},trim:String.prototype.trim?function(b){return b.trim()}:function(b){return b.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},replace:function(b,k,l){return b.replace(l||s,r.isFunction(k)?k:function(a,b){return r.getObject(b,!1,k)})}};r.mixin(m,r);return r})},"dojo/has":function(){define(["require","module"],function(m,h){var d=m.has||function(){};d.add("dom-addeventlistener",!!document.addEventListener);d.add("touch","ontouchstart"in document||navigator.maxTouchPoints||window.navigator.msMaxTouchPoints);
d.add("touch-events","ontouchstart"in document);d.add("pointer-events",navigator.maxTouchPoints);d.add("MSPointer",navigator.msMaxTouchPoints);d.add("device-width",screen.availWidth||innerWidth);var q=document.createElement("form");d.add("dom-attributes-explicit",0==q.attributes.length);d.add("dom-attributes-specified-flag",0<q.attributes.length&&40>q.attributes.length);d.clearElement=function(d){d.innerHTML="";return d};d.normalize=function(q,h){var m=q.match(/[\?:]|[^:\?]*/g),s=0,r=function(b){var k=
m[s++];if(":"==k)return 0;if("?"==m[s++]){if(!b&&d(k))return r();r(!0);return r(b)}return k||0};return(q=r())&&h(q)};d.load=function(d,q,h){d?q([d],h):h()};return d})},"dojo/_base/kernel":function(){define(["../has","./config","require","module"],function(m,h,d,q){var t,u={},w={},s={config:h,global:this,dijit:u,dojox:w},u={dojo:["dojo",s],dijit:["dijit",u],dojox:["dojox",w]};q=d.map&&d.map[q.id.match(/[^\/]+/)[0]];for(t in q)u[t]?u[t][0]=q[t]:u[t]=[q[t],{}];for(t in u)q=u[t],q[1]._scopeName=q[0],
h.noGlobals||(this[q[0]]=q[1]);s.scopeMap=u;s.baseUrl=s.config.baseUrl=d.baseUrl;s.isAsync=d.async;s.locale=h.locale;q="$Rev$".match(/[0-9a-f]{7,}/);s.version={major:1,minor:10,patch:0,flag:"-pre",revision:q?q[0]:NaN,toString:function(){var b=s.version;return b.major+"."+b.minor+"."+b.patch+b.flag+" ("+b.revision+")"}};Function("d","d.eval \x3d function(){return d.global.eval ? d.global.eval(arguments[0]) : eval(arguments[0]);}")(s);s.exit=function(){};"undefined"!=typeof console||(console={});var u=
"assert count debug dir dirxml error group groupEnd info profile profileEnd time timeEnd trace warn log".split(" "),r;for(q=0;r=u[q++];)console[r]||function(){var b=r+"";console[b]="log"in console?function(){var k=Array.prototype.slice.call(arguments);k.unshift(b+":");console.log(k.join(" "))}:function(){};console[b]._fake=!0}();m.add("dojo-debug-messages",!!h.isDebug);s.deprecated=s.experimental=function(){};m("dojo-debug-messages")&&(s.deprecated=function(b,k,l){b="DEPRECATED: "+b;k&&(b+=" "+k);
l&&(b+=" -- will be removed in version: "+l);console.warn(b)},s.experimental=function(b,k){var l="EXPERIMENTAL: "+b+" -- APIs subject to change without notice.";k&&(l+=" "+k);console.warn(l)});if(h.modulePaths){s.deprecated("dojo.modulePaths","use paths configuration");m={};for(t in h.modulePaths)m[t.replace(/\./g,"/")]=h.modulePaths[t];d({paths:m})}s.moduleUrl=function(b,k){s.deprecated("dojo.moduleUrl()","use require.toUrl","2.0");var l=null;b&&(l=d.toUrl(b.replace(/\./g,"/")+(k?"/"+k:"")+"/*.*").replace(/\/\*\.\*/,
"")+(k?"":"/"));return l};s._hasResource={};return s})},"dojo/promise/Promise":function(){define(["../_base/lang"],function(m){function h(){throw new TypeError("abstract");}return m.extend(function(){},{then:function(d,q,m){h()},cancel:function(d,q){h()},isResolved:function(){h()},isRejected:function(){h()},isFulfilled:function(){h()},isCanceled:function(){h()},always:function(d){return this.then(d,d)},otherwise:function(d){return this.then(null,d)},trace:function(){return this},traceRejected:function(){return this},
toString:function(){return"[object Promise]"}})})},"xstyle/core/Proxy":function(){define("xstyle/core/Proxy",["xstyle/core/utils"],function(m){function h(d){void 0!==d&&this.setSource(d)}var d=m.when;h.prototype={property:function(d){var m=this.hasOwnProperty("_properties")?this._properties:this._properties={},u=m[d];if(u)return u;u=m[d]=new h(this.get(d));u.parent=this;u.name=d;return u},observe:function(d){(this._listeners||(this._listeners=[])).push(d);void 0!==this.source&&d(this.valueOf())},
setSource:function(q){var h=this;this.handle&&this.handle.remove&&this.handle.remove();d(q,function(d){h.source=d;for(var q=h._listeners||0,s=h.valueOf(),m=0;m<q.length;m++)q[m](s);d&&d.observe&&(h.handle=d.observe(function(b){for(var k=h._listeners||0,l=0;l<k.length;l++)k[l](b)}));q=h._properties;for(m in q)h.property(m).setSource(d&&d.property&&d.property(m))})},valueOf:function(){var d=this.source;return d&&d.observe?d.valueOf():d},get:function(d){var h=this.source;return h?h.get?h.get(d):h[d]:
this["value-"+d]},set:function(d,h){var m=this.source;m?m[d]=h:this["value-"+d]=h;(m=this._properties&&this._properties[d])&&m.put(h)},put:function(d){var h=this.source;if(h&&h.put)return h.put(d);this.parent&&(this.parent[this.name]=d);return this.setSource(d)}};return h})},"xstyle/core/base":function(){define("xstyle/core/base","xstyle/core/elemental xstyle/core/expression xstyle/core/utils put-selector/put xstyle/core/Rule dojo/Deferred xstyle/core/Proxy".split(" "),function(m,h,d,q,t,u,w){function s(a,
b,f,e){return{forElement:function(p,d){var k=p;e&&(p=p.parentNode);if(b)for(;!p.matches(b.selector);)if(p=p.parentNode,!p)throw Error("Rule not found");if(f)for(;!(a in p);)if(p=p.parentNode,!p)throw Error(a?a+" not found":"Property was never defined");d&&(p["_"+a+"Node"]=k);(k=p[a])?k.observe||(k=new w(k)):k=p[a]=new w(null);k.element=p;k.newElement=e;return k},define:function(b,f){return s(a||b,f,e)},put:function(b){m.addRenderer(function(f){var g=f[a];g&&g.put?g.put(b):f[a]=new w(b)})}}}function r(a,
b,f,e){var p=h.evaluate(a,f);p.forElement?m.addRenderer(a,function(a){e(p.forElement(a),a)}):e(p)}function b(a,b){return{apply:function(f,e,p){r(f,p,e[0],function(e,x){e.observe(function(e){e=e?a:b;value.toString().replace(RegExp(a+"\\([^)]+\\)","g"),e);x?x.style[p]=e:f.setStyle(p,e)})})}}}var k=q("div"),l=navigator.userAgent,a=-1<l.indexOf("WebKit")?"-webkit-":-1<l.indexOf("Firefox")?"-moz-":-1<l.indexOf("MSIE")?"-ms-":-1<l.indexOf("Opera")?"-o-":"",e;t=new t;t.root=!0;t.definitions={Math:Math,window:window,
global:window,module:h.selfResolving(function(a,b){a[0].value&&(a=a[0].value);b||require([a]);return{then:function(b){var e=new u;require([a],function(a){e.resolve(b(a))});return e.promise}}}),item:s("item",null,!0),"page-content":s("page-content",{selector:"body"},!0),content:s("content",null,!0,function(a){this.element}),"element-property":s(),element:{forElement:function(a){return{element:a,observe:function(b){b(a)},get:function(a){return this.element[a]}}}},event:{observe:function(a){a(e)}},each:{forParent:function(a){return{put:function(b){a.each=
b}}}},prefix:{forParent:function(b,e){return{put:function(f){if("string"==typeof k.style[a+e])return b._setStyleFromValue(a+e,f),!0}}}},"var":function(a,b){var f=Object.create(a),e;for(e in b)f[e]=b[e];return f}(new w,{forParent:function(a,b){var f=a.variables||(a.variables=new w),e=f.property(b),d=this;e.observe=function(f){var k;w.prototype.observe.call(e,function(a){k=a;f(a)});void 0===k&&a.parent&&d.forParent(a.parent,b).observe(function(a){void 0===k&&f(a)})};e.valueOf=function(){var e=f[b];
if(void 0!==e)return e;if(a.parent)return d.forParent(a.parent,b).valueOf()};return e},apply:function(a,b){return this.forParent(a,b[0])}}),inline:b("inline","none"),block:b("block","none"),visible:b("visible","hidden"),"extends":{apply:function(a,b){for(;0<b.length;)return d.extend(a,b[0],console.error)}},set:h.contextualized(function(a,b){a.put(b)}),get:h.resolved(function(a){return a}),on:{forParent:function(a,b){return{put:function(f){m.on(document,b.slice(3),a.selector,function(b){e=b;var g=
h.evaluate(a,f);g&&g.forElement&&(g=g.forElement(b.target));g&&g.stop&&g.stop();e=null})}}}},"@supports":{selector:function(a){function b(a){var c;if(c=a.match(/^\s*not(.*)/))return!b(c[1]);if(c=a.match(/\((.*)\)/))return b(c[1]);if(c=a.match(/([^:]*):(.*)/))return a=d.convertCssNameToJs(c[1]),c=k.style[a]=c[2],k.style[a]==c;if(c=a.match(/\w+\[(.*)=(.*)\]/))return q(c[0])[c[1]]==c[2];if(c=a.match(/\w+/))return d.isTagSupported(c);throw Error("can't parse @supports string");}b(a.selector.slice(10))?
a.selector="":a.disabled=!0}},"true":!0,"false":!1,"null":null};t.elementProperty=s;return t})},"dojo/errors/create":function(){define(["../_base/lang"],function(m){return function(h,d,q,t){q=q||Error;var u=function(h){if(q===Error){Error.captureStackTrace&&Error.captureStackTrace(this,u);var m=Error.call(this,h),r;for(r in m)m.hasOwnProperty(r)&&(this[r]=m[r]);this.message=h;this.stack=m.stack}else q.apply(this,arguments);d&&d.apply(this,arguments)};u.prototype=m.delegate(q.prototype,t);u.prototype.name=
h;return u.prototype.constructor=u}})},"xstyle/core/utils":function(){define("xstyle/core/utils",[],function(){var m={};return{when:function(h,d){return h&&h.then?h.then(d)||h:d(h)},convertCssNameToJs:function(h){return h.replace(/-(\w)/g,function(d,h){return h.toUpperCase()})},isTagSupported:function(h){if(h in m)return m[h];var d=document.createElement(h).toString();return m[h]=!("[object HTMLUnknownElement]"==d||"[object]"==d)},extend:function(h,d,m){var t=d.split(".");d=t[0];var u=h.getDefinition(d,
"rules");t[0]="";h.selector+=h.extraSelector=t.join(".");if(u)return this.when(u,function(d){if(d.extend)d.extend(h,!0);else for(var m in d)h[m]=d[m]});h.tagName=d;this.isTagSupported(d)||m("Extending undefined definition "+d)}}})},"dojo/_base/array":function(){define(["./kernel","../has","./lang"],function(m,h,d){function q(b){return w[b]=new Function("item","index","array",b)}function t(b){var d=!b;return function(l,a,e){var c=0,g=l&&l.length||0,f;g&&"string"==typeof l&&(l=l.split(""));"string"==
typeof a&&(a=w[a]||q(a));if(e)for(;c<g;++c){if(f=!a.call(e,l[c],c,l),b^f)return!f}else for(;c<g;++c)if(f=!a(l[c],c,l),b^f)return!f;return d}}function u(b){var d=1,l=0,a=0;b||(d=l=a=-1);return function(e,c,g,f){if(f&&0<d)return r.lastIndexOf(e,c,g);f=e&&e.length||0;var x=b?f+a:l;g===s?g=b?l:f+a:0>g?(g=f+g,0>g&&(g=l)):g=g>=f?f+a:g;for(f&&"string"==typeof e&&(e=e.split(""));g!=x;g+=d)if(e[g]==c)return g;return-1}}var w={},s,r={every:t(!1),some:t(!0),indexOf:u(!0),lastIndexOf:u(!1),forEach:function(b,
d,l){var a=0,e=b&&b.length||0;e&&"string"==typeof b&&(b=b.split(""));"string"==typeof d&&(d=w[d]||q(d));if(l)for(;a<e;++a)d.call(l,b[a],a,b);else for(;a<e;++a)d(b[a],a,b)},map:function(b,d,l,a){var e=0,c=b&&b.length||0;a=new (a||Array)(c);c&&"string"==typeof b&&(b=b.split(""));"string"==typeof d&&(d=w[d]||q(d));if(l)for(;e<c;++e)a[e]=d.call(l,b[e],e,b);else for(;e<c;++e)a[e]=d(b[e],e,b);return a},filter:function(b,d,l){var a=0,e=b&&b.length||0,c=[],g;e&&"string"==typeof b&&(b=b.split(""));"string"==
typeof d&&(d=w[d]||q(d));if(l)for(;a<e;++a)g=b[a],d.call(l,g,a,b)&&c.push(g);else for(;a<e;++a)g=b[a],d(g,a,b)&&c.push(g);return c},clearCache:function(){w={}}};d.mixin(m,r);return r})},"xstyle/core/expression":function(){define("xstyle/core/expression",["xstyle/core/utils"],function(m){function h(a,b){return m.when(a,d(function(a){var c=b[0];return!a?a:c&&a.property?h(a.property(c),b.slice(1)):c?h(a[c],b.slice(1)):a}))}function d(a){return function(b){return b&&b.forElement?{forElement:function(c){return a(b.forElement(c))}}:
a(b)}}function q(a,b){for(var c=0,e=a.length;c<e;c++){var g=a[c];if(g&&"object"==typeof g&&b in g)return!0}}function t(a){a.selfResolving=!0;return a}function u(a,b){return t(function E(){var c=arguments,e;if(E.skipResolve)e=c;else{e=[];for(var g=0,d=c.length;g<d;g++)e[g]=l(this,c[g])}return a[b?"call":"apply"](this,e)})}function w(a,b){return u(function(c){return q(c,"then")?{then:function(e,g){function d(){l--;l||e(a[b?"call":"apply"](this,k))}for(var l=1,k=[],v=0;v<c.length;v++){var h=c[v];h&&
h.then?(l++,function(a){h.then(function(b){k[a]=b;d()},g)}(v)):(k[v]=h,d())}d()}}:a[b?"call":"apply"](this,c)},!0)}function s(b,c){return w(function(e){e.id=a++;return q(e,"forElement")?{forElement:function(a){for(var g,d,l=[],k=0,v=e.length;k<v;k++){(d=e[k])&&d.forElement&&(d=d.forElement(a,1==d.length));l[k]=d;var h=d=d.element;if(g)for(;d&&d!=g;)d=d.parentNode;d&&(g=h)}a=g["expr-result-"+e.id];a||(g["expr-result-"+e.id]=a=b[c?"call":"apply"](this,l))&&(a.element=g);return a}}:b[c?"call":"apply"](this,
e)},!0)}function r(a,b){return s(function(c){function e(){for(var b=[],d=0,g=c.length;d<g;d++){var l=c[d];b[d]=l&&l.valueOf()}return a.apply(this,b)}if(q(c,"observe")){var d={observe:function(a){for(var b=0,f=c.length;b<f;b++){var d=c[b];d&&d.observe&&d.observe(function(){a(e())})}},valueOf:function(){return e()}};b&&q(c,"put")&&(d.put=function(a){b(a,c)});return d}return e()},!0)}function b(a){return c[a]||(c[a]=new Function("a","b","return "+a))}function k(a,c,d,l,k){function h(a){a.skipResolve=
!0;a.precedence=c;a.infix=!0===l||!!k}var m=function(a,b){var c=b[0],f=b[1];if(c&&c.put)f=l(a,f&&f.valueOf()),f!==e&&c.put(f);else if(f&&f.put)f.put(k(a,c&&c.valueOf()));else throw new TypeError("Can not put");},y=function(){var c;d=b(d);l=l&&b(l);k=k&&b(k);g[a]=c=r(d,m);h(c);return c.apply(this,arguments)};h(y);g[a]=y}function l(a,b){function c(b){for(;q>=b.precedence;){var e=y.pop(),d=g[y.pop()],e=d.apply(a,d.infix?[y.pop(),e]:[e]);v=y.length&&y[y.length-1];y.push(e);q=v&&g[v]&&g[v].precedence}}
var e,d;b=b.join?b.slice():[b];for(e=0;e<b.length;e++)if(d=b[e],"string"==typeof d){d=d.match(/"[^\"]*"|[+-\/\?\:^*!&|]+|[\w_$\.\/-]+/g);var k=[e,1];d&&k.push.apply(k,d);b.splice.apply(b,k);e+=k.length-3}var q,y=[],v;for(e=0;e<b.length;e++){d=b[e];if("("==d.operator){var s=y.pop();d=function(b){return m.when(s,function(c){c.selfResolving||(c=r(c));return c.apply(a,b)})}(d.getArgs())}else if(g.hasOwnProperty(d))k=g[d],c(k),q=(v||k).precedence;else if(-1<d)d=+d;else if(d.isLiteralString)d=d.value;else{d=
d.split(/\s*\/\s*/);var k=d[0],A=a.getDefinition(k);if("string"==typeof A||A instanceof Array)A=l(a,A);else if(void 0===A)throw Error('Could not find reference "'+k+'"');1<d.length&&(A=h(A,d.slice(1)));d=A}y.push(d)}c({precedence:1});return y[0]}var a=1,e={},c={},g={};k("+",5,"a+b","a-b","a-b");k("-",5,"a-b","a+b","b-a");k("*",6,"a*b","a/b","a/b");k("/",6,"a/b","a*b","b/a");k("^",7,"a^b","a^(-b)","Math.log(a)/Math.log(b)");k("?",2,"b[a?0:1]","a\x3d\x3d\x3db[0]||(a\x3d\x3d\x3db[1]?false:deny)","[a,b]");
k(":",3,"[a,b]","a[0]?a[1]:deny","a[1]");k("!",8,"!a","!a");return{resolved:u,ready:w,contextualized:s,react:r,observe:function(a,b){return a&&a.observe?a.observe(b):b(a)},evaluate:l,selfResolving:t}})},"dojo/sniff":function(){define(["./has"],function(m){var h=navigator,d=h.userAgent,h=h.appVersion,q=parseFloat(h);m.add("air",0<=d.indexOf("AdobeAIR"));m.add("msapp",parseFloat(d.split("MSAppHost/")[1])||void 0);m.add("khtml",0<=h.indexOf("Konqueror")?q:void 0);m.add("webkit",parseFloat(d.split("WebKit/")[1])||
void 0);m.add("chrome",parseFloat(d.split("Chrome/")[1])||void 0);m.add("safari",0<=h.indexOf("Safari")&&!m("chrome")?parseFloat(h.split("Version/")[1]):void 0);m.add("mac",0<=h.indexOf("Macintosh"));m.add("quirks","BackCompat"==document.compatMode);if(d.match(/(iPhone|iPod|iPad)/)){var t=RegExp.$1.replace(/P/,"p"),u=d.match(/OS ([\d_]+)/)?RegExp.$1:"1",u=parseFloat(u.replace(/_/,".").replace(/_/g,""));m.add(t,u);m.add("ios",u)}m.add("android",parseFloat(d.split("Android ")[1])||void 0);m.add("bb",
(0<=d.indexOf("BlackBerry")||0<=d.indexOf("BB10"))&&parseFloat(d.split("Version/")[1])||void 0);m.add("trident",parseFloat(h.split("Trident/")[1])||void 0);m.add("svg","undefined"!==typeof SVGAngle);m("webkit")||(0<=d.indexOf("Opera")&&m.add("opera",9.8<=q?parseFloat(d.split("Version/")[1])||q:q),0<=d.indexOf("Gecko")&&(!m("khtml")&&!m("webkit")&&!m("trident"))&&m.add("mozilla",q),m("mozilla")&&m.add("ff",parseFloat(d.split("Firefox/")[1]||d.split("Minefield/")[1])||void 0),document.all&&!m("opera")&&
(d=parseFloat(h.split("MSIE ")[1])||void 0,(h=document.documentMode)&&(5!=h&&Math.floor(d)!=h)&&(d=h),m.add("ie",d)),m.add("wii","undefined"!=typeof opera&&opera.wiiremote));return m})},"put-selector/put":function(){(function(m){var h,d=/[-+,> ]/;m([],h=function(m,t){function u(k){function l(){f&&(g&&f!=g)&&(g==k&&(a||(a=d.test(D)&&m.createDocumentFragment()))?a:g).insertBefore(f,c||null)}for(var a,e,c,g,f,h=arguments,p=h[0],E=0;E<h.length;E++){var D=h[E];if("object"==typeof D){e=!1;if(D instanceof
Array){f=m.createDocumentFragment();for(var t=0;t<D.length;t++)f.appendChild(u(D[t]));D=f}if(D.nodeType)f=D,l(),g=D,c=0;else for(t in D)f[t]=D[t]}else if(e)e=!1,f.appendChild(m.createTextNode(D));else{1>E&&(k=null);e=!0;if(p=D.replace(w,function(a,e,d,p,A,t){e&&(l(),"-"==e||"+"==e?(g=(c=f||g).parentNode,f=null,"+"==e&&(c=c.nextSibling)):("\x3c"==e?g=f=(f||g).parentNode:(","==e?g=k:f&&(g=f),f=null),c=0),f&&(g=f));if((a=!d&&p)||!f&&(d||A))"$"==a?(a=h[++E],g.appendChild(m.createTextNode(a))):(a=a||u.defaultTag,
(e=b&&h[E+1]&&h[E+1].name)&&(a="\x3c"+a+' name\x3d"'+e+'"\x3e'),f=r&&~(s=a.indexOf("|"))?m.createElementNS(r[a.slice(0,s)],a.slice(s+1)):m.createElement(a));if(d)if("$"==p&&(p=h[++E]),"#"==d)f.id=p;else if(e=(a=f.className)&&(" "+a+" ").replace(" "+p+" "," "),"."==d)f.className=a?(e+p).substring(1):p;else if("!"==D){var w;b?u("div",f,"\x3c").innerHTML="":(w=f.parentNode)&&w.removeChild(f)}else e=e.substring(1,e.length-1),e!=a&&(f.className=e);A&&("$"==t&&(t=h[++E]),"style"==A?f.style.cssText=t:(d=
"!"==A.charAt(0)?(A=A.substring(1))&&"removeAttribute":"setAttribute",t=""===t?A:t,r&&~(s=A.indexOf("|"))?f[d+"NS"](r[A.slice(0,s)],A.slice(s+1),t):f[d](A,t)));return""}))throw new SyntaxError("Unexpected char "+p+" in "+D);l();g=p=f||g}}k&&a&&k.appendChild(a);return p}d=t||d;var w=/(?:\s*([-+ ,<>]))?\s*(\.|!\.?|#)?([-\w%$|]+)?(?:\[([^\]=]+)=?['"]?([^\]'"]*)['"]?\])?/g,s,r=!1;m=m||document;var b="object"==typeof m.createElement;u.addNamespace=function(b,d){m.createElementNS?(r||(r={}))[b]=d:m.namespaces.add(b,
d)};u.defaultTag="div";u.forDocument=h;return u})})(function(m,h,d){d=d||h;"function"===typeof define?define([],function(){return d()}):"undefined"==typeof window?require("./node-html")(module,d):put=d()})},"dojo/promise/instrumentation":function(){define(["./tracer","../has","../_base/lang","../_base/array"],function(m,h,d,q){function t(b,a,e){var c="";b&&b.stack&&(c+=b.stack);a&&a.stack&&(c+="\n    ----------------------------------------\n    rejected"+a.stack.split("\n").slice(1).join("\n").replace(/^\s+/,
" "));e&&e.stack&&(c+="\n    ----------------------------------------\n"+e.stack);console.error(b,c)}function u(b,a,e,c){a||t(b,e,c)}function w(d,a,e,c){a?q.some(r,function(a,b){if(a.error===d)return r.splice(b,1),!0}):q.some(r,function(a){return a.error===d})||r.push({error:d,rejection:e,deferred:c,timestamp:(new Date).getTime()});b||(b=setTimeout(s,k))}function s(){var d=(new Date).getTime(),a=d-k;r=q.filter(r,function(b){return b.timestamp<a?(t(b.error,b.rejection,b.deferred),!1):!0});b=r.length?
setTimeout(s,r[0].timestamp+k-d):!1}h.add("config-useDeferredInstrumentation","report-unhandled-rejections");var r=[],b=!1,k=1E3;return function(b){var a=h("config-useDeferredInstrumentation");if(a){m.on("resolved",d.hitch(console,"log","resolved"));m.on("rejected",d.hitch(console,"log","rejected"));m.on("progress",d.hitch(console,"log","progress"));var e=[];"string"===typeof a&&(e=a.split(","),a=e.shift());if("report-rejections"===a)b.instrumentRejected=u;else if("report-unhandled-rejections"===
a||!0===a||1===a)b.instrumentRejected=w,k=parseInt(e[0],10)||k;else throw Error("Unsupported instrumentation usage \x3c"+a+"\x3e");}}})},"dojo/promise/tracer":function(){define(["../_base/lang","./Promise","../Evented"],function(m,h,d){function q(d){setTimeout(function(){u.apply(t,d)},0)}var t=new d,u=t.emit;t.emit=null;h.prototype.trace=function(){var d=m._toArray(arguments);this.then(function(h){q(["resolved",h].concat(d))},function(h){q(["rejected",h].concat(d))},function(h){q(["progress",h].concat(d))});
return this};h.prototype.traceRejected=function(){var d=m._toArray(arguments);this.otherwise(function(h){q(["rejected",h].concat(d))});return this};return t})},"dojo/_base/config":function(){define(["../has","require"],function(m,h){var d={},q=h.rawConfig,t;for(t in q)d[t]=q[t];if(!d.locale&&"undefined"!=typeof navigator&&(q=navigator.language||navigator.userLanguage))d.locale=q.toLowerCase();return d})},"xstyle/core/elemental":function(){define("xstyle/core/elemental",["put-selector/put"],function(m){function h(a,
b,c,e){function d(a){(!c||l.call(a.target,c))&&e(a)}r?a.addEventListener(b,d,!1):a.attachEvent(b,d)}function d(a){/e/.test(w.readyState||"")?setTimeout(a,200):w.addEventListener("DOMContentLoaded",a)}function q(a){for(var b=w.querySelectorAll(a.selector),c=a.name,d=0,g=b.length;d<g;d++){var k=b[d],l=k.elementalStyle;l||(l=k.elementalStyle={},k.elementalSpecificities={});var h=k.renderings;h||(h=k.renderings=[],e.push(k));h.push({name:c,rendered:l[c]==a.propertyValue,renderer:a});l[c]=a.propertyValue}}
function t(){for(var a=0;a<e.length;a++){var b=e[a],c=b.renderings,d=b.elementalStyle;delete b.renderings;for(var k=0;k<c.length;k++){var l=c[k],h=l.renderer,y=h.rendered;g=d[l.name]==h.propertyValue;if(!y&&g)try{h.render(b)}catch(v){console.error(v,v.stack),m(b,"div.error",v.toString())}y&&(!g&&h.unrender)&&(h.unrender(b),c.splice(k--,1))}}e=[]}function u(b,c){for(var d=0,e=a.length;d<e;d++){var g=a[d];(!c||c==g.selector)&&(l?l.call(b,g.selector):b.currentStyle[g.id])&&g.render(b)}}var w=document,
s=1,r=!!w.addEventListener;h(w,"change",null,function(a){a=a.target;var b=a["-x-variable"];b&&(b.forElement&&(b=b.forElement(a)),b&&b.put&&b.put(a.value))});var b=w.createElement("div"),k={"dom-qsa2.1":!!b.querySelectorAll},l=b.matches||b.matchesSelector||b.webkitMatchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector,a=[],e=[],c;d(function(){if(!c)if(c=!0,k["dom-qsa2.1"]){for(var b=0,d=a.length;b<d;b++)q(a[b]);t()}else for(var e=w.all,b=0,d=e.length;b<d;b++)u(e[b])});var g;
return{ready:d,on:h,addRenderer:function(b,d){var e={selector:b.selector,render:d};l||b.setStyle(e.id="x"+s++,"true");a.push(e);c&&q(e);t()},update:u,clearRenderers:function(){a=[]}}})},"xstyle/main":function(){define("xstyle/main",["require","xstyle/core/parser","xstyle/core/base","xstyle/core/elemental","xstyle/core/generate"],function(m,h,d,q,t){function u(b){b=document.getElementsByTagName(b);for(var d=0;d<b.length;d++)s(b[d])}function w(){u("link");u("style")}function s(b,d,l){function a(){m(["xstyle/core/load-imports"],
function(a){a(b,function(){s(b,d,!0)})})}function e(a){for(var b=a.cssRules,c=0;c<b.length;c++){var e=b[c];if(e.selectorText&&"x-"==e.selectorText.substring(0,2)&&(g=!0,/^'/.test(e.style.content)))return r(eval(e.style.content),a,d),!0}}var c=b.sheet||b.styleSheet;if(c){var g=c.needsParsing,f=c.rules||c.cssRules;if((c.href||c.imports&&c.imports.length)&&!l)return a();if(!g)for(var h=0;h<f.length;h++){var p=f[h];if(p.href&&!l){if(!e(p.styleSheet))return a();return}}r(c.localSource||(c.ownerNode||c.owningElement).innerHTML,
c,d)}}function r(b,k,l){k.addRule||(k.addRule=function(a,b,d){return this.insertRule(a+"{"+b+"}",0<=d?d:this.cssRules.length)});k.deleteRule||(k.deleteRule=k.removeRule);var a=1;(k.href||location.href).replace(/[^\/]+$/,"");d.css=b;h(d,b,k);0==--a&&l&&l(k);return d}q.ready(w);h.getStyleSheet=function(b,d){return b.styleSheet||b};return{process:s,processAll:w,parse:r,generate:t,load:function(b,d,h,a){d(["xstyle/css"],function(e){e.load(b,d,function(a){a?s({sheet:a},h):(w(),h())},a)})}}})},"xstyle/core/parser":function(){define("xstyle/core/parser",
["xstyle/core/utils"],function(m){function h(){this.push.apply(this,arguments)}function d(a){this.value=a}function q(){var a,b=this.args[0];if("string"==typeof b)a=b.split(/\s*,\s*/);else{a=[];for(var c=0,d=0;d<b.length+1;d++){var f=b[d];if("string"==typeof f||void 0===f)if(f=f&&f.split(/\s*,\s*/),1<a.length||void 0===f){var k=b.slice(c,d);0<c&&k.unshift(a.pop());c=d+1;a.push(k);f&&a.push.apply(a,f.slice(1))}}}return a}function t(a,e,c){function g(c,e){function F(a){G=!1;var b=l.lastIndex;a.then(function(){G=
!0;c&&(l.lastIndex=b,N())});var c=!0}function N(){function a(b){b&&("string"==typeof b&&N)&&(b=N+b);z?z.push?"string"==typeof z[z.length-1]&&"string"==typeof b?z[z.length-1]+=b:b&&z.push(b):"string"==typeof z&&"string"==typeof b?z+=b:z=new h(z,b):z=b}for(G=!0;G;){var s=l.exec(c);if(!s)break;var H=s[5],N=s[1],C=s[2],O=s[3],J=s[4],L,M,z,ca,J=J&&k(J),C=C&&k(C);I?(O?(M=C,L=O.charAt(0),ca="?"==O.charAt(1),-1<O.indexOf("\n")&&(J=O.slice(1))):J=C,z=J,I=!1):(J=O?C+O:C,a(J));"{"!=H&&(K+=s[0]);switch(H){case "'":case '"':var V=
"'"==H?u:w;V.lastIndex=l.lastIndex;(H=V.exec(c))||y("unterminated string");C=H[1];l.lastIndex=V.lastIndex;a(new d(C));K+=H[0];continue;case "\\":H=V.lastIndex++;a(c.charAt(H));continue;case "(":case "{":case "[":var B,da=!1;if("{"==H){I=!0;":"==L&&O&&(C+=O);K=k((K+C).replace(/\s+/g," ").replace(/([\.#:])\S+|\w+/g,function(a,b){return b?a:a.toLowerCase()}));a(B=v.newRule(K));"\x3d"==L&&(U=!1,z.creating=!0,J&&J.match(/^\w/)&&(da=!0));":"==L&&!v.root&&(z.creating=!0);var P=null,ea=A;if(s[6]&&(O=e.cssRules||
e.rules,B.cssRule=P=O[s[6].slice(1)]))K=P.selectorText;if(v.root&&U)for(O=e.cssRules||e.rules;P=O[A++];)if(P.selectorText==K){B.cssRule=P;break}P||(B.ruleIndex=A=ea,B.styleSheet=e);z.creating?(B.selector="."+("\x3d"==L?C.match(/[\w-]*$/g,"")[0]:"")+"-x-"+b++,B.creating=!0):B.selector=v.root?K:v.selector+" "+K;K=""}else C=J.match(/(.*?)([\w-]*)$/),a(B=v.newCall(C[2],z,v)),B.ref=v.getDefinition(C[2]),B.getArgs=q,(z.calls||(z.calls=[])).push(B);B.parent=v;da&&J.replace(/(?:^|\s+)([\w-\.]+)\s*$/g,function(a,
b){var c=m.extend(B,b,y);c&&c.then&&F(c)});v.currentName=M;v.currentSequence=z;v.assignmentOperator=L;var W;if("{"==H&&(W=B.selector.match(/[@:]\w+/)))W=W[0],(M=v.getDefinition(W))&&M.selector&&M.selector(B);p.push(v=B);v.operator=H;v.start=l.lastIndex;z=M=null;continue}if(z)if(C="string"==typeof z?z:z[0],C.charAt&&"@"==C.charAt(0))if(J=C.match(/\w+/)[0],"import"==J)C=t.getStyleSheet((e.cssRules||e.imports)[A++],z,e),J=l.lastIndex,g(C.localSource,C),l.lastIndex=J;else{if("xstyle"==J){if("start"==
C.slice(8,13))B=v?v.newRule(""):X,B.root=v.root,B.parent=v,p.push(v=B);else{var X=v||X;p.pop();v=p[p.length-1]}l=v?f:/(@[\w\s])/g}}else if(L)try{var S=v[":"==L?"setValue":"declareDefinition"](M,z,ca);S&&S.then&&F(S)}catch(ua){y(ua)}switch(H){case ":":"\x3d"==L?(I=!0,L=":"):a(":");break;case "}":case ")":case "]":r[v.operator]!=H&&y("Incorrect opening operator "+v.operator+" with closing operator "+H);M=null;M=c.slice(v.start,l.lastIndex-1);v.cssText=v.cssText?v.cssText+";"+M:M;if("}"==H){"}"==fa&&
(fa=v.parent.selector)&&"@"==!fa.charAt(0)&&y("A nested rule must end with a semicolon");if(v.root)y("Unmatched "+H);else{try{v.onRule(v.selector,v)}catch(ma){y(ma)}U=!0}K=""}if(")"==H&&!L){v.args=[z];try{S=p[p.length-2].onArguments(v)}catch(Ha){y(Ha)}S&&S.then&&F(S)}p.pop();v=p[p.length-1];z=v.currentSequence;M=v.currentName;L=v.assignmentOperator;if(v.root&&"}"==H){if(L)try{v[":"==L?"setValue":"declareDefinition"](M,z[1]||z,ca)}catch(va){y(va)}I=!0;L=!1}break;case "":case void 0:return;case ";":z=
null,I=!0,L=U=!1,K=""}var fa=H}}function y(a){var b=(e.href||"in-page stylesheet")+":"+c.slice(0,l.lastIndex).split("\n").length;if(g.onerror)g.onerror(a,b);console.error(a.message||a,b);a.stack&&console.error(a.stack)}c=c.replace(s,function(a){return a.replace(/[^\n]/g,"")});var v=a;l.lastIndex=0;var G,A=0,U=!0,K="",I=!0;N()}c=c||{addRule:function(){},cssRules:[]};var f,l=f=/(\s*)((?:[^{\}\[\]\(\)\\'":=;]|\[(?:[^\]'"]|'(?:\\.|[^'])*'|"(?:\\.|[^"])*")\])*)([=:]\??\s*([^{\}\[\]\(\)\\'":;]*))?(?:([{\}\[\]\(\)\\'":;])(\/\d+)?|$)/g,
p=[a];a.parse=g;g(e,c)}var u=/((?:\\.|[^'])*)'/g,w=/((?:\\.|[^"])*)"/g,s=/\/\*[\w\W]*?\*\//g,r={"{":"}","[":"]","(":")"},b=0,k="".trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")},l=h.prototype=[];l.toString=function(){return this.join("")};l.isSequence=!0;d.prototype.toString=function(){return'"'+this.value.replace(/["\\\n\r]/g,"\\$\x26")+'"'};d.prototype.isLiteralString=!0;return t})},"dojo/Evented":function(){define(["./aspect","./on"],function(m,h){function d(){}
var q=m.after;d.prototype={on:function(d,m){return h.parse(this,d,m,function(d,h){return q(d,"on"+h,m,!0)})},emit:function(d,m){var q=[this];q.push.apply(q,arguments);return h.emit.apply(h,q)}};return d})},"dojo/errors/CancelError":function(){define(["./create"],function(m){return m("CancelError",null,null,{dojoType:"cancel"})})},"dojo/Deferred":function(){define(["./has","./_base/lang","./errors/CancelError","./promise/Promise","./promise/instrumentation"],function(m,h,d,q,t){var u=Object.freeze||
function(){},w=function(b,a,d,c,g){2===a&&(k.instrumentRejected&&0===b.length)&&k.instrumentRejected(d,!1,c,g);for(g=0;g<b.length;g++)s(b[g],a,d,c)},s=function(d,a,e,c){var g=d[a],f=d.deferred;if(g)try{var h=g(e);if(0===a)"undefined"!==typeof h&&b(f,a,h);else{if(h&&"function"===typeof h.then){d.cancel=h.cancel;h.then(r(f,1),r(f,2),r(f,0));return}b(f,1,h)}}catch(m){b(f,2,m)}else b(f,a,e);2===a&&k.instrumentRejected&&k.instrumentRejected(e,!!g,c,f.promise)},r=function(d,a){return function(e){b(d,a,
e)}},b=function(b,a,d){if(!b.isCanceled())switch(a){case 0:b.progress(d);break;case 1:b.resolve(d);break;case 2:b.reject(d)}},k=function(b){var a=this.promise=new q,e=this,c,g,f,h=!1,m=[];Error.captureStackTrace&&(Error.captureStackTrace(e,k),Error.captureStackTrace(a,k));this.isResolved=a.isResolved=function(){return 1===c};this.isRejected=a.isRejected=function(){return 2===c};this.isFulfilled=a.isFulfilled=function(){return!!c};this.isCanceled=a.isCanceled=function(){return h};this.progress=function(b,
d){if(c){if(!0===d)throw Error("This deferred has already been fulfilled.");return a}w(m,0,b,null,e);return a};this.resolve=function(b,d){if(c){if(!0===d)throw Error("This deferred has already been fulfilled.");return a}w(m,c=1,g=b,null,e);m=null;return a};var r=this.reject=function(b,d){if(c){if(!0===d)throw Error("This deferred has already been fulfilled.");return a}Error.captureStackTrace&&Error.captureStackTrace(f={},r);w(m,c=2,g=b,f,e);m=null;return a};this.then=a.then=function(b,d,e){var h=
[e,b,d];h.cancel=a.cancel;h.deferred=new k(function(a){return h.cancel&&h.cancel(a)});c&&!m?s(h,c,g,f):m.push(h);return h.deferred.promise};this.cancel=a.cancel=function(a,e){if(c){if(!0===e)throw Error("This deferred has already been fulfilled.");}else{if(b){var f=b(a);a="undefined"===typeof f?a:f}h=!0;if(c){if(2===c&&g===a)return a}else return"undefined"===typeof a&&(a=new d),r(a),a}};u(a)};k.prototype.toString=function(){return"[object Deferred]"};t&&t(k);return k})},"dojo/aspect":function(){define([],
function(){function m(d,h,b,k){var l=d[h],a="around"==h,e;if(a){var c=b(function(){return l.advice(this,arguments)});e={remove:function(){c&&(c=d=b=null)},advice:function(a,b){return c?c.apply(a,b):l.advice(a,b)}}}else e={remove:function(){if(e.advice){var a=e.previous,c=e.next;!c&&!a?delete d[h]:(a?a.next=c:d[h]=c,c&&(c.previous=a));d=b=e.advice=null}},id:q++,advice:b,receiveArguments:k};if(l&&!a)if("after"==h){for(;l.next&&(l=l.next););l.next=e;e.previous=l}else"before"==h&&(d[h]=e,e.next=l,l.previous=
e);else d[h]=e;return e}function h(h){return function(r,b,k,l){var a=r[b],e;if(!a||a.target!=r)r[b]=e=function(){for(var a=q,b=arguments,f=e.before;f;)b=f.advice.apply(this,b)||b,f=f.next;if(e.around)var h=e.around.advice(this,b);for(f=e.after;f&&f.id<a;){if(f.receiveArguments)var k=f.advice.apply(this,b),h=k===d?h:k;else h=f.advice.call(this,h,b);f=f.next}return h},a&&(e.around={advice:function(b,d){return a.apply(b,d)}}),e.target=r;r=m(e||a,h,k,l);k=null;return r}}var d,q=0,t=h("after"),u=h("before"),
w=h("around");return{before:u,around:w,after:t}})},"xstyle/core/generate":function(){define("xstyle/core/generate","xstyle/core/elemental put-selector/put xstyle/core/utils xstyle/core/expression xstyle/core/base xstyle/core/Proxy".split(" "),function(m,h,d,q,t,u){function w(a,b){a=a.sort?a:[a];return function(c,g,f){var k=c;c._defaultBinding=!1;if(void 0===f){var p=c.childNodes,r=p[0],t;if(r){t=l.createDocumentFragment();do t.appendChild(r);while(r=p[0])}}c.content=t;for(var u=0,w=[c],y=[],p=0,r=
a.length;p<r;p++){var v=G,G=a[p];try{if(G.eachProperty)if(G.args)if("("==G.operator){var A=a[p+1];A&&A.eachProperty&&h(k,A.selector);var U=G.getArgs()[0],K=q.evaluate(G.parent,U);s(k,A,K,b,U)}else h(k,G.toString());else h(k,G.selector),y.push(G.selector,k);else if("string"==typeof G){"\x3d"==G.charAt(0)&&(G=G.slice(1));var I=k,A=a[p+1],Z=[];G.replace(/([,\n]+)?([\t ]+)?(\.|#)?([-\w%$|\.\#]+)(?:\[([^\]=]+)=?['"]?([^\]'"]*)['"]?\])?/g,function(){Z.push(arguments)});for(var ka=0;ka<Z.length;ka++)(function(a,
l,m,p,q,r,s){function G(){var a=I._contentNode;a&&(a.innerHTML="",I=a)}m?l?(a=m.length,a>u?(G(),w[a]=I):I=w[a]||I,u=a):G():G();var t;if(p)t=(v&&v.args?"":"span")+p+q;else{p=q.match(/^[-\w]+/)[0];var E=b.getDefinition(p);E&&(E.then||E.newElement)?function(a,b,c,e){var f,g;d.when(E,function(b){b.newElement?(f=b.newElement(),(c=c.slice(e.length))&&h(a,c)):f=h(c);if(g){g.parentNode.replaceChild(f,g);b=g.childNodes;var d;for(f=f._contentNode||f;d=b[0];)f.appendChild(d)}});f?a.insertBefore(f,b||null):(g=
h("span"),a=a.insertBefore(g,b||null))}(I,f,q,p):t=q}t&&(I=h(f||I,(f?"-":"")+t));f=null;r&&I.setAttribute(r,""===s?r:s);g&&(I.item=g);(ka<Z.length-1||I!=k&&I!=c&&(!A||!A.base))&&y.push(null,I);k=I}).apply(this,Z[ka])}else k.appendChild(l.createTextNode(G.value))}catch(H){console.error(H,H.stack),k.appendChild(l.createTextNode(H))}}for(;elementToUpdate=y.pop();)m.update(elementToUpdate,y.pop());return k}}function s(a,e,c,g,f){var m=a.content||(a.content=new u);d.when(c,function(b){b.forElement&&(b=
b.forElement(a));b.forParent&&(b=b.forParent(g,f));m.setSource(b)});if(!("_defaultBinding"in a)){a._defaultBinding=!0;var p=a.appendChild(l.createTextNode("Loading"));m.observe(function(c){if(a._defaultBinding)if(c&&c.sort)if(p&&(p.parentNode.removeChild(p),p=null),c.isSequence)w(c,part.parent)(a,item,beforeElement);else{a.innerHTML="";var d=e&&e.eachProperty&&e.each,f=e.newRule(),d=d?w(d,f):function(a,c,d){return h(d||a,(d?"-":"")+(b[a.tagName]||"span"),""+c)},g=c.map(function(b){return d(a,b,null)});
c.observe&&c.observe(function(b,c,e){if(-1<c){var f=g[c];f.parentNode.removeChild(f);g.splice(c,1)}-1<e&&g.splice(e,0,d(a,b,g[e]||null))},!0)}else c&&c.nodeType?(p&&(p.parentNode.removeChild(p),p=null),a.appendChild(c)):(c=void 0===c?"":c,a.tagName in k?(a.value=c,a["-x-variable"]=m):p.nodeValue=c)})}}function r(a,b){return w(b,t)(a)}var b={TABLE:"tr",TBODY:"tr",TR:"td",UL:"li",OL:"li",SELECT:"option"},k={INPUT:1,TEXTAREA:1,SELECT:1},l=document;r.forSelector=w;return r})},"dojo/on":function(){define(["./has!dom-addeventlistener?:./aspect",
"./_base/kernel","./sniff"],function(m,h,d){function q(a,b,c,f,g){if(f=b.match(/(.*):(.*)/))return b=f[2],f=f[1],s.selector(f,b).call(g,a,c);d("touch")&&(r.test(b)&&(c=N(c)),!d("event-orientationchange")&&"orientationchange"==b&&(b="resize",a=window,c=N(c)));e&&(c=e(c));if(a.addEventListener){var h=b in l,k=h?l[b]:b;a.addEventListener(k,c,h);return{remove:function(){a.removeEventListener(k,c,h)}}}if(x&&a.attachEvent)return x(a,"on"+b,c);throw Error("Target must be an event emitter");}function t(){this.cancelable=
!1;this.defaultPrevented=!0}function u(){this.bubbles=!1}var w=window.ScriptEngineMajorVersion;d.add("jscript",w&&w()+ScriptEngineMinorVersion()/10);d.add("event-orientationchange",d("touch")&&!d("android"));d.add("event-stopimmediatepropagation",window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);d.add("event-focusin",function(a,b,c){return"onfocusin"in c});var s=function(a,b,c,d){return"function"==typeof a.on&&"function"!=typeof b&&!a.nodeType?a.on(b,c):s.parse(a,
b,c,q,d,this)};s.pausable=function(a,b,c,d){var e;a=s(a,b,function(){if(!e)return c.apply(this,arguments)},d);a.pause=function(){e=!0};a.resume=function(){e=!1};return a};s.once=function(a,b,c,d){var e=s(a,b,function(){e.remove();return c.apply(this,arguments)});return e};s.parse=function(a,b,c,d,e,f){if(b.call)return b.call(f,a,c);if(b instanceof Array)g=b;else if(-1<b.indexOf(","))var g=b.split(/\s*,\s*/);if(g){var h=[];b=0;for(var k;k=g[b++];)h.push(s.parse(a,k,c,d,e,f));h.remove=function(){for(var a=
0;a<h.length;a++)h[a].remove()};return h}return d(a,b,c,e,f)};var r=/^touch/;s.selector=function(a,b,c){return function(d,e){function f(b){g=g&&g.matches?g:h.query;1!=b.nodeType&&(b=b.parentNode);for(;!g.matches(b,a,d);)if(b==d||!1===c||!(b=b.parentNode)||1!=b.nodeType)return;return b}var g="function"==typeof a?{matches:a}:this,k=b.bubble;return k?s(d,k(f),e):s(d,b,function(a){var b=f(a.target);return b&&e.call(b,a)})}};var b=[].slice,k=s.emit=function(a,c,d){var e=b.call(arguments,2),f="on"+c;if("parentNode"in
a){var g=e[0]={},h;for(h in d)g[h]=d[h];g.preventDefault=t;g.stopPropagation=u;g.target=a;g.type=c;d=g}do a[f]&&a[f].apply(a,e);while(d&&d.bubbles&&(a=a.parentNode));return d&&d.cancelable&&d},l=d("event-focusin")?{}:{focusin:"focus",focusout:"blur"};if(!d("event-stopimmediatepropagation"))var a=function(){this.modified=this.immediatelyStopped=!0},e=function(b){return function(c){if(!c.immediatelyStopped)return c.stopImmediatePropagation=a,b.apply(this,arguments)}};if(d("dom-addeventlistener"))s.emit=
function(a,b,c){if(a.dispatchEvent&&document.createEvent){var d=(a.ownerDocument||document).createEvent("HTMLEvents");d.initEvent(b,!!c.bubbles,!!c.cancelable);for(var e in c)e in d||(d[e]=c[e]);return a.dispatchEvent(d)&&d}return k.apply(s,arguments)};else{s._fixEvent=function(a,b){a||(a=(b&&(b.ownerDocument||b.document||b).parentWindow||window).event);if(!a)return a;try{c&&(a.type==c.type&&a.srcElement==c.target)&&(a=c)}catch(d){}if(!a.target)switch(a.target=a.srcElement,a.currentTarget=b||a.srcElement,
"mouseover"==a.type&&(a.relatedTarget=a.fromElement),"mouseout"==a.type&&(a.relatedTarget=a.toElement),a.stopPropagation||(a.stopPropagation=p,a.preventDefault=E),a.type){case "keypress":var e="charCode"in a?a.charCode:a.keyCode;10==e?(e=0,a.keyCode=13):13==e||27==e?e=0:3==e&&(e=99);a.charCode=e;e=a;e.keyChar=e.charCode?String.fromCharCode(e.charCode):"";e.charOrCode=e.keyChar||e.keyCode}return a};var c,g=function(a){this.handle=a};g.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};
var f=function(a){return function(b){b=s._fixEvent(b,this);var d=a.call(this,b);b.modified&&(c||setTimeout(function(){c=null}),c=b);return d}},x=function(a,b,c){c=f(c);if(((a.ownerDocument?a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=top||5.8>d("jscript"))&&!d("config-_allow_leaks")){"undefined"==typeof _dojoIEListeners_&&(_dojoIEListeners_=[]);var e=a[b];if(!e||!e.listeners){var h=e,e=Function("event","var callee \x3d arguments.callee; for(var i \x3d 0; i\x3ccallee.listeners.length; i++){var listener \x3d _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");
e.listeners=[];a[b]=e;e.global=this;h&&e.listeners.push(_dojoIEListeners_.push(h)-1)}e.listeners.push(a=e.global._dojoIEListeners_.push(c)-1);return new g(a)}return m.after(a,b,c,!0)},p=function(){this.cancelBubble=!0},E=s._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1;this.modified=!0}}if(d("touch"))var D=function(){},F=window.orientation,N=function(a){return function(b){var c=b.corrected;if(!c){var e=
b.type;try{delete b.type}catch(f){}if(b.type){if(d("mozilla")){var c={},g;for(g in b)c[g]=b[g]}else D.prototype=b,c=new D;c.preventDefault=function(){b.preventDefault()};c.stopPropagation=function(){b.stopPropagation()}}else c=b,c.type=e;b.corrected=c;if("resize"==e){if(F==window.orientation)return null;F=window.orientation;c.type="orientationchange";return a.call(this,c)}"rotation"in c||(c.rotation=0,c.scale=1);var e=c.changedTouches[0],h;for(h in e)delete c[h],c[h]=e[h]}return a.call(this,c)}};
return s})}}});(function(){var m=this.require;m({cache:{}});!m.async&&m(["dojo"]);m.boot&&m.apply(null,m.boot)})();
//@ sourceMappingURL=dojo.js.map